#!/usr/bin/env bash
# Run the full test suite + benchmarks and save everything to results/<label>.md.
#
#   scripts/test-report.sh              # label = current tag/commit (git describe)
#   scripts/test-report.sh ep03         # explicit label
#   CRITERION=1 scripts/test-report.sh  # also run the in-memory criterion bench (~15 min)
#
# The file is meant to be committed next to the code it measured.
set -uo pipefail

cd "$(dirname "$0")/.."
command -v cargo >/dev/null || export PATH="$HOME/.cargo/bin:$PATH"

label="${1:-$(git describe --tags --always --dirty)}"
out="results/${label}.md"
mkdir -p results
tmp="$(mktemp)"
metrics="$(mktemp)"
trap 'rm -f "$tmp" "$metrics"' EXIT

echo "building release..."
cargo build --release --all-targets >/dev/null 2>&1 || { echo "build failed"; exit 1; }

echo "running tests..."
# One test thread: deterministic output order, and timing-sensitive tests
# (CPU, memory, crash) don't compete with each other.
cargo test --release -- --test-threads=1 >"$tmp" 2>&1
test_status=$?
echo "collecting measured values..."
for t in cpu memory crash; do
  cargo test --release --test "$t" -- --nocapture --test-threads=1 2>&1 \
    | grep -E 'B/key|leaked|freed|growth|connection|CPU|acknowledged writes' \
    | sed -E 's/^test [a-z_0-9]+ \.\.\. //' >>"$metrics"
done
passed=$(grep -o '[0-9]* passed' "$tmp" | awk '{s+=$1} END {print s+0}')
failed=$(grep -o '[0-9]* failed' "$tmp" | awk '{s+=$1} END {print s+0}')

bench="target/release/rkv-bench"
echo "benchmarking stores..."
stores="$("$bench" --compare stores -c 50 -n 20000 2>&1)"
echo "benchmarking fsync policies..."
fsync="$("$bench" --compare fsync -c 50 -n 2000 2>&1)"

criterion=""
if [[ "${CRITERION:-0}" == 1 ]]; then
  echo "running criterion (slow)..."
  criterion="$(cargo bench --bench store 2>&1 | grep -E '^store|thrpt:')"
fi

cpu="$(powershell.exe -NoProfile -Command '(Get-CimInstance Win32_Processor).Name' 2>/dev/null | tr -d '\r' \
  || grep -m1 'model name' /proc/cpuinfo 2>/dev/null | cut -d: -f2 \
  || sysctl -n machdep.cpu.brand_string 2>/dev/null)"

{
  echo "# Test report: \`${label}\`"
  echo
  echo "| | |"
  echo "|---|---|"
  echo "| Result | $([[ $test_status == 0 ]] && echo "**PASS**" || echo "**FAIL**"): ${passed} passed, ${failed} failed |"
  echo "| Commit | \`$(git rev-parse --short HEAD)\` $(git log -1 --format=%s) |"
  echo "| Date | $(date '+%Y-%m-%d %H:%M %Z') |"
  echo "| Machine | ${cpu:-unknown}, $(nproc 2>/dev/null || echo '?') logical CPUs, $(uname -s) |"
  echo "| Toolchain | $(rustc --version) |"
  echo
  echo "Generated by \`scripts/test-report.sh\`. Methodology and what each test asserts: [docs/PERFORMANCE.md](../docs/PERFORMANCE.md)."
  echo
  echo "## Benchmark: stores over TCP"
  echo
  echo "$stores"
  echo
  echo "## Benchmark: WAL fsync policies over TCP (sharded store)"
  echo
  echo "$fsync"
  echo
  if [[ -n "$criterion" ]]; then
    echo "## Benchmark: in-memory stores (criterion, million ops/sec = Melem/s)"
    echo
    echo '```'
    echo "$criterion"
    echo '```'
    echo
  fi
  echo "## Measured values printed by the tests"
  echo
  echo '```'
  cat "$metrics"
  echo '```'
  echo
  echo "## Test results"
  echo
  echo '```'
  # Drop test binaries that contain no tests (main.rs, rkv-bench, doc-tests).
  grep -E '^\s*Running |^\s*Doc-tests |^test .* \.\.\. |^test result:|panicked at|^failures:' "$tmp" \
    | sed -E 's/ \(target[^)]*\)//' \
    | awk '/^ *(Running|Doc-tests) / { hdr = $0; next }
           /^test result: ok\. 0 passed/ { hdr = ""; next }
           { if (hdr != "") { print hdr; hdr = "" } print }'
  echo '```'
} >"$out"

echo "wrote $out ($passed passed, $failed failed)"
exit $test_status
